spring:
  application:
    name: ApnaMart

  datasource:
    url: jdbc:mysql://localhost:3306/apnamart
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      # properties:
      # hibernate.dialect: org.hibernate.dialect.MySQLDialect
    # show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host:
    port:
    username:
    password:
    protocol:
    properties:
      mail.smtp.auth:
      mail.smtp.starttls.enable:

server:
  port:
  # servlet:
  #   context-path: /am

# SMS Configuration
twilio:
  account-sid:
  auth-token:
  phone-number:

# Logging
# logging:
#   level:
#     root: WARN
#     org.springframework.security: DEBUG

# Hibernate SQL Formatting
# spring:
#   jpa:
#     show-sql: true
#     properties:
#       hibernate.format_sql: true
