spring:
  application:
    name: ApnaMart

  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}

  frontend:
    url: ${FRONTEND_URL}

  jpa:
    hibernate:
      ddl-auto: update
      # properties:
      # hibernate.dialect: org.hibernate.dialect.MySQLDialect
    # show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${PROTOCOL}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE}

server:
  port:${SERVER_PORT}
  # servlet:
  #   context-path: /am

# SMS Configuration
twilio:
  account-sid: ${ACCOUNT_SID}
  auth-token: ${AUTH_TOKEN}
  phone-number: ${PHONE_NUMBER}

# Logging
# logging:
#   level:
#     root: WARN
#     org.springframework.security: DEBUG

# Hibernate SQL Formatting
# spring:
#   jpa:
#     show-sql: true
#     properties:
#       hibernate.format_sql: true
